### ISSUE TITLE
Nested rule doesn't consume all needed backgrounds

### ISSUE THREAD

**Issue by elchupanebrej** [cucumber/gherkin#126]
### 👓 What did you see?

```python
feature = """
Feature: Nested rules
  Background:
    Given Feature background

  Rule: Outer rule
    Background:
      Given Outer rule background step

    Rule: Nested rule
      Background:
        Given Nested background rule step

      Example:
        Then Scenario step
"""

from gherkin.parser import Parser
from gherkin.pickles.compiler import Compiler
parser = Parser()
gherkin_document = parser.parse(feature)
gherkin_document["uri"] = 'local'
pickles = Compiler().compile(gherkin_document)
```

I get next pickle:

```python
[{'astNodeIds': ['8'],
  'id': '3',
  'language': 'en',
  'name': '',
  'steps': [{'astNodeIds': ['0'],
             'id': '0',
             'text': 'Feature background',
             'type': 'Context'},
            {'astNodeIds': ['5'],
             'id': '1',
             'text': 'Nested background rule step',
             'type': 'Context'},
            {'astNodeIds': ['7'],
             'id': '2',
             'text': 'Scenario step',
             'type': 'Outcome'}],
  'tags': [],
  'uri': 'local'}]
```

so `Outer rule background step` is missing in the pickle

### ✅ What did you expect to see?

All 4 steps from every level background is present in the pickle

### 📦 Which tool/library version are you using?
Python 3.10.9
gherkin-official              24.1.0
----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by luke-hill** [comment]
I'm 95% certain we test this in our acceptance tests. However you are using quite an old version (So it maybe something we've only introduced recently).

I do know python is one of the versions that has slightly less usage, that might be why.

**Comment by mpkorstanje** [comment]
A quick guess would be that we fixed this somewhere after the mono repo split. We haven't released the python module since.  https://github.com/cucumber/gherkin/issues/148.

**Comment by elchupanebrej** [comment]
gherkin-official 29.0 - Reproduced

**Comment by luke-hill** [comment]
My understanding is all `Rule` tags are considered top level. This is because you can't have 2 background references within a rule.

I would expect your sample to equate to

Outer Rule: Given feature background / Given outer rule (No steps)
Inner Rule: Given feature background / Given Inner (1 step)

But I'm sure this may be something that I'm not 100% au faix with. It definitely should live in either gherkin testing as testdata golden or in the CCK proper. CCK currently has this: https://github.com/cucumber/compatibility-kit/blob/main/devkit/samples/rules/rules.feature 

Rule has this: https://github.com/cucumber/gherkin/blob/main/testdata/good/rule.feature

Because the concept of tabbing in gherkin isn't concrete, I would say that your tabbing here a misnomer and based on the tests written above, that my understanding is probably what is happening. Can you confirm this?

**Comment by elchupanebrej** [comment]
@luke-hill Thank you for your explanation. It seems that nested rules are not supported. I expected that rules could be deeply nested and that every rule would add its own background at the top of the example steps.

**Comment by luke-hill** [comment]
@elchupanebrej - Ironically I found a long standing issue to update the docs that would cover this situation here: https://github.com/cucumber/docs/issues/561 I never got around to doing it though
