### ISSUE TITLE
Python: Automate releases

### ISSUE THREAD

**Issue by ehuelsmann** [cucumber/gherkin#148]
Same as cucumber/tag-expressions#20 and related to #62, @aslakhellesoy noted:

> We've adopted a release process based on GitHub Actions - documented in [RELEASING.md](https://github.com/cucumber/.github/blob/main/RELEASING.md)
> 
> In order to automate Python releases, we need a new .github/workflows/release-pypi.yml

**Comment by ehuelsmann** [comment]
https://github.com/cucumber/action-publish-pypi exists and can be integrated..

**Comment by ehuelsmann** [comment]
@jenisys when you're looking at tag-expressions, please have a look at this project too.

**Comment by ehuelsmann** [comment]
Also take #40 into account.

**Comment by jenisys** [comment]
@ehuelsmann 
I just looked at it. I think I do not have the sufficient rights for this project that is registered with https://pypi.org . Only @aslakhellesoy and the cukebot are registered as maintainers. If Aslak can register me there as maintainer, then I could perform the necessary steps (or Aslak can perform the necessary steps).

NOTE:
This is different with `tag-expressions`. Because I created this project on https://pypi.org , I am also the maintainer (and added Aslak afterwards as maintainer). Therefore, there I can create the necessary build-token that can be used later-on. 

SEE ALSO:
* https://pypi.org/project/gherkin-official/

**Comment by aslakhellesoy** [comment]
The automated release process outlined in https://github.com/cucumber/.github/blob/main/RELEASING.md uses the `cukebot` account for releases. We made a decision a while ago to avoid using personal accounts.

What's preventing you from using the automated release process @jenisys?

**Comment by mpkorstanje** [comment]
PiPy credenrials have been restored.

So now it comes down to merging and possibly updating https://github.com/cucumber/gherkin/pull/62 but we don't have any dedicated Python maintainers in the core team so it may take a while.

**Comment by brasmusson** [comment]
Fixed with #213
