### ISSUE TITLE
Implement Gherkin in Rust

### ISSUE THREAD

**Issue by dvberkel** [cucumber/gherkin#181]
I was thinking of a project to work on in [Rust](https://www.rust-lang.org) and cucumber sprang to mind. I saw that a Gherkin3 parser in Rust was on the wish list. I read the [CONTRIBUTING.md](https://github.com/cucumber/gherkin/blob/master/CONTRIBUTING.md) and love the rationale behind keeping the code as similar as possible. I am starting this issue to see if there is still an interest, if people are already are working on it and general and tricks.

It probably goes without saying that I can not fully commit to delivering a complete implementation, but I am willing to gain some experience.

**Comment by aslakhellesoy** [comment]
Oh absolutely @dvberkel! We'd love a Rust implementation.

Feel free to ask questions in this ticket or in the [gitter chat room](https://gitter.im/cucumber/gherkin). I'd be happy to guide you. It's a fun challenge. Some people have been able to deliver a fully working parser and compiler in 3-4 days - to give you an idea. How much time it actually takes obviously depends on a lot of other factors.

Thanks for offering to contribute - looking forward to helping you out!

**Comment by dyule** [comment]
Hey @dvberkel I was just about to open a very similar issue.  I'd be quite pleased to help out with implementing a Rust parser.

**Comment by dvberkel** [comment]
Hi @dyule that is great news! I have not really started working on a Rust implementation yet. I first wanted to explore the project to get a feel for how other languages are implementing Gherkin.

It would be great to work together. Let's see how things develop.

**Comment by dvberkel** [comment]
@dyule I just made you collaborator to my fork of Gherkin. I figured it would be the easiest way to collaborate. If you are uncomfortable working on my fork, feel free to let my know.

**Comment by dvberkel** [comment]
I have opened [issues](https://github.com/dvberkel/gherkin/issues) on my fork to discuss implementation details for the Rust parser

**Comment by aslakhellesoy** [comment]
The next release of Gherkin will have a CLI. It's currently fully implemented in C, .NET, Java, JavaScript, Python and Ruby.

Theoretically, we only need one implementation now (could be the C one since it's fast and cross platform).

The Gherkin CLI takes a list of files and outputs a `source`, `gherkin-document` and `pickle` events according to the [Cucumber Event Protocol](https://docs.cucumber.io/event-protocol/).

A Cucumber implementation in Rust could just shell out to the CLI to get parsed Gherkin documents as JSON docs (by reading those events).

I'm therefore going to discourage more implementations of Gherkin in other languages.
