### ISSUE TITLE
Add support for "active" tags in gherkin

### ISSUE THREAD

**Issue by dg-ratiodata** [cucumber/gherkin#195]
**Background:**

In `behave` (https://github.com/behave/behave) there are tags available known as "active tags". In `aruba` we use quite a few tags which look similar to this one `@unsupported-on-ruby-older-193` to work around ruby version problems or just some other library which is broken in version "X.Y".

aruba: [features/development/test.feature](https://github.com/cucumber/aruba/blob/1939c4049d5195ffdd967485f50119bdd86e98a0/features/development/test.feature#L17):

``` gherkin
  @unsupported-on-ruby-older-193
  Scenario: Testing compliance to ruby community guide
    Given I successfully run `rubocop`
    Then the features should all pass
```

**Feature Request:**

What I'd love to see is:

``` gherkin
  @required-ruby: >= 1.9.3
  Scenario: Testing compliance to ruby community guide
    Given I successfully run `rubocop`
    Then the features should all pass
```

And this:

Not sure, if this syntax is a good one. Maybe it should look different and is an implementation detail of `cucumber-ruby`.

``` ruby
Before '@required-ruby' do |argument, matcher|
  # I had no better idea how to express my idea... as using the rspec syntax
  skip_this_scenario if expect(argument).to matcher(RUBY_VERSION)
end
```

Or run features with tag-filter with argument given to tag:

``` bash
cucumber --tag @required-ruby:1.9.3
```

Things to discuss - I think there are more to discuss
- [ ] Is this a good thing to have such tags
- [ ] Are matchers accepted
- [ ] Which matchers are accepted - eg. =, <=, >=, <, >, != or <>, =~
- [ ] No matcher given equals = ?

Ping @cucumber/core As there also needs to be some implementation on the cucumber\* side.

@mattwynne Hope it's ok to open an issue for that. I really like the idea of having such kind of tags.

**Comment by aslakhellesoy** [comment]
I didn't quite understand active tags when they were explained to me.

What's wrong with this:

```gherkin
@ruby-193-or-greater
Scenario: Testing compliance to ruby community guide
  Given I successfully run `rubocop`
  Then the features should all pass
```

```ruby
Before '@ruby-193-or-greater' do
  skip_this_scenario if RUBY_VERSION < '1.9.3'
end
```

**Comment by dg-ratiodata** [comment]
You could have a single `Before`-hook for each single version which is much easier to read and means less code.

So with just

~~~ruby
Before '@required-ruby' do |argument, matcher|
  # I had no better idea how to express my idea... as using the rspec syntax
  skip_this_scenario if expect(argument).to matcher(RUBY_VERSION)
end
~~~

You could handle all cases given below:

~~~cucumber
@required-ruby: < 1.9.3
Scenario: Testing compliance to ruby community guide
  Given I successfully run `rubocop`
  Then the features should all pass

@required-ruby: <> 1.9.3
Scenario: Testing compliance to ruby community guide
  Given I successfully run `rubocop`
  Then the features should all pass

@required-ruby: >= 1.9.3
Scenario: Testing compliance to ruby community guide
  Given I successfully run `rubocop`
  Then the features should all pass
~~~

**Comment by charlierudolph** [comment]
As far as gherkin is concerned, I would think this is simply allowing tags to have optional arguments. If a tag is followed by a colon, the rest of the line is the tag argument. And the benefit of this is the user can write a single function to deal with the tag and its argument. Very interesting idea.

---

A possible alternative to the problem you are describing could be the following:

Use the following tags
```gherkin
@required-ruby-1.9.3       # exactly 1.9.3
@required-ruby-not-1.9.3   # not 1.9.3
@required-ruby-lt-1.9.3    # less than 1.9.3
@required-ruby-gte-1.9.3   # greater then or equal to 1.9.3
```
And implement tag matching in the following way
```rb
# match based on regexp instead of exact match
Before '@required-ruby-*' do 
  # Given some way to access the matching tag
  # Parse the tag and do the proper skipping
end
```

**Comment by enkessler** [comment]
I like the idea of being able to match/filter tags based on a regex in addition to exact match..

**Comment by maxmeyer** [comment]
@enkessler Added =~ to the list of matchers.

**Comment by jenisys** [comment]
@aslakhellesoy 
An "active tag" determines at runtime from the test environment or the SUT if a certain condition is met. By doing this, it normally requires the following:

* prefix (or suffix) that allows to easily distinguish between "active tags" and "normal tags"
* category: describes what is needed or of interest
* comparison-operator: In most cases equal-to or ...
* value (that the category must match or mismatch)

SCHEMA, like: "@use_with.{category}={value}"   (but a different naming scheme was discussed in this thread)
Therefore, the "active tag" is only enabled if the category has the specified value.

Example:
A scenario makes only sense when you run it under a certain operating system like Windows, Linux, OSX etc. By using an active tag, the scenario is automatically skipped when the condition is not matched.

```gherkin
@use_with.os=windows
Scenario: Requires Windows to run
   Given ...

@not_with.os=windows
Scenario: Runs on all OS except Windows
   Given ...
```

SEE ALSO:
* behave docs: [Active Tags](http://python-behave.readthedocs.org/en/latest/new_and_noteworthy_v1.2.5.html#active-tags)
* behave [features/tags.active_tags.feature](https://github.com/behave/behave/blob/master/features/tags.active_tags.feature)

But note that similar concepts exist in most test frameworks (to skip tests at runtime when it does not make sense to run them because some condition is not met). Therefore, active tags make this concept available for Gherkin and the cucumber family.
