### ISSUE TITLE
The one and only Haxe target

### ISSUE THREAD

**Issue by bsideup** [cucumber/gherkin#234]
Hi! 

Currently, Gherkin is implemented for each language individually, so every change should be ported to every language.

Luckily, there is http://haxe.org/ - nice language which compiles to target languages, i.e. C/C++, Java, JS, ActionScript, Lua, PHP, Python, C#, Objective-C, etc...

So we can implement the parser in Haxe and then generate target-specific code.

There are some existing implementations as well, such as https://github.com/haxeui/haxe-bdd/tree/master/gherkin

WDYT?

**Comment by aslakhellesoy** [comment]
That's a great idea! We're also experimenting with a CLI around Gherkin, which is another strategy for a single parser to be the one and only.

But a Haxe parser might still be super nice!

Ping us on https://gitter.im/cucumber/contributors to discuss!

**Comment by aslakhellesoy** [comment]
The next release of Gherkin will have a CLI. It's currently fully implemented in C, .NET, Java, JavaScript, Python and Ruby.

Theoretically, we only need one implementation now (could be the C one since it's fast and cross platform).

The Gherkin CLI takes a list of files and outputs a `source`, `gherkin-document` and `pickle` events according to the [Cucumber Event Protocol](https://docs.cucumber.io/event-protocol/).

A Cucumber implementation in Haxe could just shell out to the CLI to get parsed Gherkin documents as JSON docs (by reading those events).

I'm therefore going to discourage more implementations of Gherkin in other languages.
