### ISSUE TITLE
Javascript:  new Gherkin.Compiler.compile(gherkinDocument, '/path/to/file.feature') doesn't write file

### ISSUE THREAD

**Issue by si-mikey** [cucumber/gherkin#238]
I have followed the examples on the javascript section. 
```js
var pickles = new Gherkin.Compiler().compile(gherkinDocument, '/home/user/test.feature');
```
doesn't write the test.feature file, though in pickles I get 

```js
[ { tags: [],
    name: 'this is a test',
    locations: [ [Object] ],
    steps: [ [Object], [Object] ] } ]
```
Does anyone know why the file is not written to the directory?

**Comment by charlierudolph** [comment]
The second argument is not an output path but the path where the gherkin document was read from. The path will appear in the pickles.

**Comment by si-mikey** [comment]
Is there a way to write to write the pickles back to a .feature file?

**Comment by charlierudolph** [comment]
There is nothing built into this library to do that.

**Comment by enkessler** [comment]
@si-mikey What would be your goal in translating the pickles back into feature files? You've already got access to the features file to begin with if you've compiled them into pickles.

**Comment by si-mikey** [comment]
@enkessler  this was me experimenting, but my goal what to build a gui to write scenarios then take that (html form) and convert it to pickles or straight to feature files to ensure proper formatting etc..

**Comment by enkessler** [comment]
Ah. So your desired flow is Form -> ugly source text -> Pickles -> pretty source text?

**Comment by si-mikey** [comment]
@enkessler  correct, this would allow people to build interfaces for gherkin writing. Do you know of a library that can do this?

**Comment by enkessler** [comment]
Off the top of my head, I only know of one. Mainly because I wrote it.

[cuke_modeler](https://github.com/enkessler/cuke_modeler)

You'll need Ruby on whatever system you end up running it on and your flow won't involve Pickles (Form -> ugly source text -> cuke_modeler models -> prety source text), but it'll get the job done.

**Comment by brasmusson** [comment]
> Is there a way to write the pickles back to a .feature file?

@si-mikey No, it is impossible to completely reproduce the feature file from the pickles, the pickles contains everything needed to execute the scenarios of the features, but not everything needed to transform the pickles back to the complete feature file.

**Comment by si-mikey** [comment]
@brasmusson what kind of things are missing from the pickles that make it impossible to translate back to feature?

**Comment by enkessler** [comment]
@si-mikey Stuff that isn't relevant to running a test, basically.

Compare the Abstract Syntax Tree for a partially complete feature file with the corresponding Pickles:

https://github.com/cucumber/gherkin/blob/master/testdata/good/incomplete_feature_1.feature.ast.json
https://github.com/cucumber/gherkin/blob/master/testdata/good/incomplete_feature_1.feature.pickles.json

The AST is the object that concerns itself with identifying and categorizing every piece of a feature file. The Pickles are only concerned about tests that need to be executed.

One could regenerate a feature file from the AST (although still not perfectly because some whitespace will be trimmed/lost during parsing). The modeling library that I linked to is essentially an abstraction layer for the AST.
